### PR TITLE
Added metrics method to PyDrill without additional classes

### PR DESCRIPTION
**Pull request by cgivre**

### CODE REVIEW

**Comment by cgivre** [comment]
It's failing Travis CI because it doesn't have a drill instance to test against.  This worked on my local environment.  Any suggestions?

**Comment by PythonicNinja** [comment]
You can mock request. 
Example:
`@responses.activate
    def test_plan_for_select_employee_mocked(self):
        sql = "SELECT * FROM cp.`employee.json` ORDER BY salary DESC LIMIT 1"

        responses.add(**{
            'method': responses.POST,
            'url': 'http://localhost:8047/query.json',
            'body': '{"queryType": "SQL","query": "explain plan for %(sql)s"}' % ({'sql': sql}),
            'status': 200,
            'content_type': 'application/json',
            'json': {},
        })

        result = self.drill.plan(sql=sql)
        assert result.response.status_code == 200`

Later on I will add support for installing instance of apache drill in test environment. So that pydrill will use real apache drill.

**Comment by cgivre** [comment]
Hi Wojtek, 
Could you take a look at the most recent pull request?
Thx,
— C

**Comment by PythonicNinja** [comment]
Hello @cgivre !

Sorry for the delay but i changed pydrill regarding testing. Now it queries real Apache Drill instance in docker env.

PR:
https://github.com/PythonicNinja/pydrill/pull/13

I will update Docs how to work with that, meanwhile it's

```
source ./run_docker
tox -e py27 # only py27 env
#or all (also isort and flake8)
tox 
```

**Comment by PythonicNinja** [comment]
@cgivre 
Already merged into master. You can take a look at https://pydrill.readthedocs.org/en/latest/readme.html#sample-usage

**Pull request closed without merging**
